### ISSUE TITLE
Error when running run_all_scripts

### ISSUE THREAD

**Issue by skodapetr** [LamprechtMatyas/MolecularSimilarity#5]
When I run ```python run_all_scripts.py -m data/configuration.json  -o data\baseline_active_pair_model.json -f ecfp.4 -p smi -d data/output_of_run_all_scripts```

where the configuration file is:
```{"model_name": "baseline_active_pair_model"}```

I got:
```
[08:37:29] SMILES Parse Error: syntax error for input: COc1ccc2[nH]cc(CC[NH+](C)C)c2c1	1832
D:\Libraries\RDKit_2015_03_1_py35\rdkit\Chem\PeriodicTable.py:131: FutureWarning: split() requires a non-empty pattern match.
  splitLine = blankExpr.split(line)
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: Cc1oc2ccc(NC(=O)c3cccs3)nc2c1CC[NH+](C)C	12094290
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: C[N@H+]1CC[C@H](Oc2cccc(NC(=O)c3ccc(F)cc3F)c2F)CC1	44216159
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: C[N@H+]1CC[C@H](c2c[nH]c3ccc(C(=O)CCc4cn[nH]c4)cc32)CC1	23003787
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: Cc1oc2ccc(NC(=O)c3ccncc3)cc2c1CC[NH+](C)C	19064681
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: N#Cc1c(Nc2ccccc2)cc[nH+]c1NCc1ccccc1	ZINC00296234
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: [NH2+]=C(N/N=C/c1cccc([N+](=O)[O-])c1)c1ccccn1	ZINC00444993
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: COc1cc(C/[NH+]=C/c2ccccc2O)cc(OC)c1	ZINC48501920
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: Oc1cc2c(cc1O)[C@@H](Cc1cc(C(F)(F)F)cc(C(F)(F)F)c1)[NH2+]CC2	ZINC11422320
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: CCC[NH2+]Cc1nc2cc(C)c(C)cc2[nH]1	ZINC51848091
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: CCC[NH2+]Cc1nc2cccc(Cl)c2[nH]1	ZINC44624095
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: CCN(CC)c1[nH]c2ccccc2[nH+]1	ZINC13110700
ERROR:root:Invalid molecule detected.
[08:37:29] SMILES Parse Error: syntax error for input: c1ccc(CCC2=[NH+]CCN2)cc1	ZINC02013186

...


[08:37:34] SMILES Parse Error: syntax error for input: Cc1ccccc1C(=O)Cc1ccc2[nH]cc([C@@H]3CC[C@H]4CCC[N@@H+]4C3)c2c1	44215145
ERROR:root:Invalid molecule detected.
[08:37:34] SMILES Parse Error: syntax error for input: Cc1oc2ccc(C(N)=O)nc2c1CC[NH+](C)C	44215225
ERROR:root:Invalid molecule detected.
[08:37:34] SMILES Parse Error: syntax error for input: C[N@H+]1CCC[C@@H]1Cc1c[nH]c2ccc(CC(=O)c3ccc(N)cc3N)cc12	23003784
ERROR:root:Invalid molecule detected.
Traceback (most recent call last):
  File "run_all_scripts.py", line 148, in <module>
    _main()
  File "run_all_scripts.py", line 86, in _main
    compute_evaluation.evaluation(activity, configuration["output"])
  File "D:\Projects\students\lamprecht-matyas\compute_evaluation.py", line 55, in evaluation
    auc = Scoring.CalcAUC(activity_arr, 0)
  File "D:\Libraries\RDKit_2015_03_1_py35\rdkit\ML\Scoring\Scoring.py", line 50, in CalcAUC
    roc = CalcROC(scores, col)
  File "D:\Libraries\RDKit_2015_03_1_py35\rdkit\ML\Scoring\Scoring.py", line 24, in CalcROC
    if numMol == 0: raise ValueError('score list is empty')
ValueError: score list is empty
```

**Comment by LamprechtMatyas** [comment]
I modified file extract_fragments.py and I hope that it will work now (it works on my computer). But I can not say, if it will work, because the previous solution worked on my computer and on yours not. So please, try it, and let me know.
